### DISCUSSION TITLE
Inquire about how to implement a script for correct constant  time verification.

### DISCUSSION THREAD

**Discussion by HOLLYwyh** [binsec/binsec#50] [Q&A] [answered]
As the title suggests, I am attempting to use binsec to verify whether the assembly code satisfies constant-time properties. Here is the assembly code that I need to verify:

```asm
intel_syntax noprefix
 .globl rawAddLL

 rawAddLL:
 Fr_rawAdd:
        mov rax, [rsi + 0]
        add rax, [rdx + 0]
        mov [rdi + 0], rax

        mov rax, [rsi + 8]
        adc rax, [rdx + 8]
        mov [rdi + 8], rax

        mov rax, [rsi + 16]
        adc rax, [rdx + 16]
        mov [rdi + 16], rax

        mov rax, [rsi + 24]
        adc rax, [rdx + 24]
        mov [rdi + 24], rax

    .type rawAddLL,@function
    .size rawAddLL,. - rawAddLL
```
This is a relatively simple addition function, and I would like to verify it using the `-checkct` feature. However, I apologize as I have only recently started working with assembly, and I've been trying to replicate the constant time verification example provided in the tutorial, but I keep encountering errors.

My understanding is as follows: I set some parts as secret and some as public, then assign certain values to them for symbolic execution to verify. Therefore, my script looks like this:

```
starting from <rawAddLL> with
    secret global rsi, rdi
    public global rdx
    assume 0x1000 <= rdi <= 0x2000
end
explore all
```
Unfortunately, it always throws an error. Could you please advise me on how to write the verification script for constant-time properties correctly and how to make it more elegant? I greatly appreciate your help, as it will be very beneficial to me. Thank you!

**Comment by recoules** [comment, marked as answer]
Hi @HOLLYwyh,

The command you are trying to use (`public` or `secret` `global`) are top level script command and requires that the names match with a global symbol in the binary.

If you want to do this, you can write a [test harness as in the tutorial](https://github.com/binsec/binsec/blob/master/doc/sse/relse.md#the-test-harness), where your inputs are global variables.

You can also directly assign secret and public value with the following syntax.
```text
starting from <rawAddLL> with
    rsi := secret
    rdi := secret
    rdx := nondet
    assume 0x1000 <= rdi <= 0x2000
end
explore all
```

*Note that you may also want to add something like `halt at <rawAddLL> + <rawAddLL:size>` to stop the analysis at the end of your chunk.*
*Still, I would suggest ending your function with a `ret` instruction and then follow the [advices given in the first tutorial](https://github.com/binsec/binsec/blob/master/doc/sse/beginners.md#script-strengthening)*.

```text
rsi := secret
rdi := secret
rdx := nondet

assume 0x1000 <= rdi <= 0x2000

starting from <rawAddLL>
with concrete stack pointer
@[rsp, 8] := 0xdeadbeef as return_address
halt at return_address

explore all
```

Regards,
Frédéric Recoules

**Reply by HOLLYwyh** [reply]
Thank you very much for your response; it’s been very helpful to me.

**Comment by HOLLYwyh** [comment]
Hello, I would like to ask one more question. My assembly code uses some constant data; for example, in the `.data section`, there is a `dq` type variable `q`, which is involved in some steps of my assembly code, such as:

```asm
        mov rax, [q + 8]
        sbb [rdi + 8], rax
```
In the process of writing the script, I used `load section .data from file` to try to load `.data`, but I noticed that the execution result was different from when I directly replaced the specific part representing the value of `q` with `[q+8]` in the assembly code. It seems that binsec is not recognizing `q`. Could you explain why this might be? Is it because I haven’t implemented the code correctly? Furthermore, would replacing `q` with its numeric value in the assembly code affect the constant-time verification?

I look forward to and appreciate your response. Thank you!

**Reply by recoules** [reply]
Hi @HOLLYwyh,

Are you compiling the assembly code to final binary or to object code only ?
In the second scenario, it may happen that the code rely on some relocations (linker directives).
BINSEC does not apply such relocations, and global variable and function symbols may be misplaced.

If you can, can you share me the file on which you ran BINSEC ?

Regards,
Frédéric Recoules

**Reply by HOLLYwyh** [reply]
I converted it to object code using the command `as file.s -o file.o`.

**Reply by recoules** [reply]
I think that all sections are given the base address `0`.
Maybe you can try to use the `-elf-alloc` flag on your BINSEC command line.

If it does not solve your issue, I would recommend writing a test harness in C and to make the program compile to a binary executable (`gcc Fr_rawAdd.s test_harness.c`).

Something like the following.

```c
extern void rawAddLL (long *r, const long *x, const long *y);

long r, x, y;

int main ()
{
  rawAddLL(&r, &x, &y)
  return 0;
}
```

**Reply by HOLLYwyh** [reply]
Hi @recoules, thank you very much for your response. I apologize that I still have some specific questions I’d like to ask you. Here is my complete code:
``` asm
.intel_syntax noprefix
.section .note.GNU-stack,"",@progbits

    .section .text
    .globl rawAddLL

rawAddLL:
        mov rax, [rsi + 0]
        add rax, [rdx + 0]
        mov [rdi + 0], rax

        mov rax, [rsi + 8]
        adc rax, [rdx + 8]
        mov [rdi + 8], rax

        mov rax, [rsi + 16]
        adc rax, [rdx + 16]
        mov [rdi + 16], rax

        mov rax, [rsi + 24]
        adc rax, [rdx + 24]
        mov [rdi + 24], rax

        jc rawAddLL_sq

        mov    rbx, 0x30644e72e131a029
        cmp rax, rbx
        jc rawAddLL_done
        jnz rawAddLL_sq


        mov rax, [rdi + 16]

        mov    rbx, 0xb85045b68181585d
        cmp rax, rbx
        jc rawAddLL_done
        jnz rawAddLL_sq


        mov rax, [rdi + 8]

        mov    rbx, 0x2833e84879b97091 
        cmp rax, rbx
        jc rawAddLL_done
        jnz rawAddLL_sq


        mov rax, [rdi + 0]

        mov    rbx, 0x43e1f593f0000001 
        cmp rax, rbx
        jc rawAddLL_done
        jnz rawAddLL_sq

rawAddLL_sq:

        mov    rbx, 0x43e1f593f0000001 
        mov rax, rbx
        sub [rdi + 0], rax
        
        mov    rbx, 0x2833e84879b97091 
        mov rax, rbx
        sbb [rdi + 8], rax

        mov    rbx, 0xb85045b68181585d
        mov rax, rbx
        sbb [rdi + 16], rax
        
        mov    rbx, 0x30644e72e131a029
        mov rax, rbx
        sbb [rdi + 24], rax

rawAddLL_done:
        ret

    .type rawAddLL,@function
    .size rawAddLL,. - rawAddLL
```
This is an addition of two large integers (`rdi = rsi + rdx`), where the numbers corresponding to `rsi` and `rdx` are at least 33 bits and at most 256 bits. I want to verify whether the `rawAddLL` function satisfies constant-time (CT) properties. We assume that the operand corresponding to `rsi` is secret, while `rdx` and `rdi` are public.

I tried using the following script:
```
## rdi = rsi + rdx

assume x = @[rsi,32]
assume y = @[rdx,32]
assume r = @[rdi,32]

x := secret
y := nondet
r := nondet

starting from <rawAddLL>
with concrete stack pointer
assume  0x100000000 <= x <= 0x100000fff
@[rsp, 8] := 0xdeadbeef as return_address
halt at return_address
explore all
```

Here's my thought process: I set the values in memory as secret/public and assumed a specific range for analysis (this is just a simple demo).

I have a few questions I’d like to consult with you:
1. I’m not sure if the format I’ve written is correct, or if my approach is conceptually sound.
2. When I ran this code, the result was “unknown,” but I was hoping to get “secure/insecure.” How should I set the appropriate parameters to ensure it explores all paths? (I noticed that the program cuts some paths during execution. Should I add certain settings to ensure it ideally doesn’t cut paths?)

**Reply by recoules** [reply]
Hi @HOLLYwyh,

Thank you for sharing your example.

First, I wish to point out that the script language is *imperative* while you seems to use *declarative* statements.
For instance, the `x := secret` writes a new secret value in `x` that will, thus, not be *backward propagated* to the preceding `assume x = @[rsi,32]` statement (where `x` is then used uninitialized).
I think the correct way to write it would be the following.
```text
@[rsi, 32] := secret as x
@[rdx, 32] := nondet as y
@[rdi, 32] := nondet as r
```
*Note that the `as` syntax is just a syntactic sugar, it does not create a strong alias. It is equivalent to the following.*
```text
x<256> := secret
@[rsi, 32] := x
``` 

Then, now I have a big picture of your code, I figure out that your inputs are given as pointer that are, themselves, symbolic by default. This may explain the issue you had previously with the `.data` section. I recommend setting the pointers to know values or, at least, give them a non overlapping value ranges.
Indeed, since `rsi`, `rdx` and `rdi` are symbolic free variables, they can overlap with each other, but also with the `.data` section or even the stack. It results that any write to them may clobber the other values, the `.data` segment or the return address of the function.

Here is an example with concrete value (offset in the stack).
```text
with concrete stack pointer
@[rsp, 8] := 0xdeadbeef as return_address
halt at return_address

rdi := rsp + 8
rsi := rsp + 40
rdx := rsp + 72

@[rsi, 32] := secret as x
@[rdx, 32] := nondet as y
@[rdi, 32] := nondet as r
```
Here is an example with concrete arbitrary ranges (you have to make sure they do not overlap with others valid addresses in the binary).
```text
assume 0x8000000000000000 <= rdi <= 0x8000000000001000
assume 0x8000000000002000 <= rsi <= 0x8000000000003000
assume 0x8000000000004000 <= rdx <= 0x8000000000005000

@[rsi, 32] := secret as x
@[rdx, 32] := nondet as y
@[rdi, 32] := nondet as r
```
Here is an example with fully relational constraints (not tested, will scale pretty badly).
```text
assume rdi + 32 <= rsi || rsi + 32 <= rdi
assume rdi + 32 <= rdx || rdx + 32 <= rdi
assume rdi + 32 <= <.data> || <.data> + <.data:size> <= rdi
assume rdi + 32 <= rsp

assume rsi + 32 <= rdx || rdx + 32 <= rsi
assume rsi + 32 <= <.data> || <.data> + <.data:size> <= rsi
assume rsi + 32 <= rsp

assume rdx + 32 <= <.data> || <.data> + <.data:size> <= rdx
assume rdx + 32 <= rsp

@[rsi, 32] := secret as x
@[rdx, 32] := nondet as y
@[rdi, 32] := nondet as r
```

With a proper initialization of pointers and data, I obtain the following result.
```text
with concrete stack pointer
@[rsp, 8] := 0xdeadbeef as return_address
halt at return_address

rdi := rsp + 8
rsi := rsp + 40
rdx := rsp + 72

@[rsi, 32] := secret as x
@[rdx, 32] := nondet as y
@[rdi, 32] := nondet as r

starting from <rawAddLL>
explore all
```
```console
$ binsec -sse -checkct -sse-script Fr_rawAdd.ini Fr_rawAdd.o -checkct-stats-file report.toml
[checkct:result] Instruction 0x0000002d has control flow leak (0.051s)
[checkct:result] Instruction 0x0000003c has control flow leak (0.056s)
[checkct:result] Instruction 0x00000042 has control flow leak (0.070s)
[checkct:result] Instruction 0x00000055 has control flow leak (0.084s)
[checkct:result] Instruction 0x00000057 has control flow leak (0.099s)
[checkct:result] Instruction 0x0000006a has control flow leak (0.113s)
[checkct:result] Instruction 0x0000006c has control flow leak (0.130s)
[checkct:result] Instruction 0x0000007e has control flow leak (0.146s)
[sse:info] Empty path worklist: halting ...
[sse:info] SMT queries
             Preprocessing simplifications
               total          41
               true           0
               false          32
               constant enum  9
             
             Satisfiability queries
               total          14
               sat            14
               unsat          0
               unknown        0
               time           0.10
               average        0.01
             
           Exploration
             total paths                      9
             completed/cut paths              9
             pending paths                    0
             stale paths                      0
             failed assertions                0
             branching points                 17
             max path depth                   45
             visited instructions (unrolled)  101
             visited instructions (static)    45
             
           
[checkct:result] Program status is : insecure (1.140)
[checkct:info] 9 visited paths covering 45 instructions
[checkct:info] 9 / 17 control flow checks pass
[checkct:info] 68 / 68 memory access checks pass
```
Where the counter examples are given in the file `report.toml`.
```toml
["CT report"."Insecurity models".0x0000002d.public]
r = ["0x000000000000000000000000000000000000000000000000000000002982b0fe"]
y = ["0x00000000000000000000000000000000000000000000000000000000221693bf"]
["CT report"."Insecurity models".0x0000002d.secret1]
x = ["0x00000000000000000000000000000000000000000000000000000000345b2a66"]
["CT report"."Insecurity models".0x0000002d.secret2]
x = ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0000003c.public]
r = ["0x000000000000000000000000000000000000000000000000000000002982b0fe"]
y = ["0x00000000000000000000000000000000000000000000000000000000221693bf"]
["CT report"."Insecurity models".0x0000003c.secret1]
x = ["0x00000000000000000000000000000000000000000000000000000000345b2a66"]
["CT report"."Insecurity models".0x0000003c.secret2]
x = ["0xa98477621b8b782152406fbf455ab2cfd3bbfcd93f9e150b048f15b8b4a397c8"]
["CT report"."Insecurity models".0x00000042.public]
r = ["0x000000000000000000000000000000000000000000000000000000002982b0fe"]
y = ["0x0000000000000000800000000000000080000000000000000000000000000001"]
["CT report"."Insecurity models".0x00000042.secret1]
x = ["0x30644e72e131a0293fffffffffffffff7fffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x00000042.secret2]
x = ["0x30644e72e131a02a3fffffffffffffffffffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x00000055.public]
r = ["0x000000000000000000000000000000000000000000000000000000002982b0fe"]
y = ["0x0000000000000000800000000000000080000000000000000000000000000001"]
["CT report"."Insecurity models".0x00000055.secret1]
x = ["0x30644e72e131a0291c5044ffc0c14c4f3fffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x00000055.secret2]
x = ["0x30644e72e131a0297c5044ffc0c14c4f3fffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x00000057.public]
r = ["0x000000000000000000000000000000000000000000000000000000002982b0fe"]
y = ["0x0000000000000000800000000000000080000000000000000000000000000001"]
["CT report"."Insecurity models".0x00000057.secret1]
x = ["0x30644e72e131a029385045b68181585d3fffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x00000057.secret2]
x = ["0x30644e72e131a029385045b68181585e3fffffffffffffffffffffffffffffff"]
["CT report"."Insecurity models".0x0000006a.public]
r = ["0x000000000000000000000000000000000000000000000000000000002982b0fe"]
y = ["0x0000000000000000800000000000000080000000000000008000000000000000"]
["CT report"."Insecurity models".0x0000006a.secret1]
x = ["0x30644e72e131a029385045b68181585ca819fc483cfd38907fffffffffffffff"]
["CT report"."Insecurity models".0x0000006a.secret2]
x = ["0x30644e72e131a029385045b68181585d7c19fc483cfd38907fffffffffffffff"]
["CT report"."Insecurity models".0x0000006c.public]
r = ["0x000000000000000000000000000000000000000000000000000000002982b0fe"]
y = ["0x0000000000000000800000000000000000000000000000008000000000000000"]
["CT report"."Insecurity models".0x0000006c.secret1]
x = ["0x30644e72e131a029385045b68181585d2833e84879b970917fffffffffffffff"]
["CT report"."Insecurity models".0x0000006c.secret2]
x = ["0x30644e72e131a029385045b68181585d2833e84879b970927fffffffffffffff"]
["CT report"."Insecurity models".0x0000007e.public]
r = ["0x000000000000000000000000000000000000000000000000000000002982b0fe"]
y = ["0x0000000000000000000000000000000000000000000000000000000000000000"]
["CT report"."Insecurity models".0x0000007e.secret1]
x = ["0x30644e72e131a029b85045b68181585d2833e84879b97091ffffffffffffffff"]
["CT report"."Insecurity models".0x0000007e.secret2]
x = ["0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000000"]
["CT report"."Instructions status"]
insecure = ["0x0000002d", "0x0000003c", "0x00000042", "0x00000055", "0x00000057", "0x0000006a", "0x0000006c", "0x0000007e"]
unknown = []
[Exploration]
branches = 17
completed_paths = 9
failed_asserts = 0
instructions = 101
max_depth = 45
paths = 9
total_asserts = 0
unique_insts = 45
unknown_paths = 0
```
Best regards,
Frédéric Recoules
